apiVersion : v1
kind : Service
metadata:
  name : {{ .Release.Name }}-{{ .Values.app.name }}
  labels :
    app : {{ .Release.Name }}-{{ .Values.app.name }}
spec:
  selector :
    app : {{ .Release.Name }}-{{ .Values.app.name }}
  ports :
    - name : {{ .Values.app.name }}
      port : {{ .Values.app.servicePort }}
      nodePort : {{ .Values.app.nodePort }}
      targetPort : {{ .Values.app.containerPort }}
  type : {{ .Values.app.serviceType }} 
  # type : nodePort 